In [1]:
import numpy as np

In [3]:
a = np.zeros((10,10))

In [4]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
a[1] = 1

In [6]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.array(list)

array(<class 'list'>, dtype=object)

In [10]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b =np.array([[0,2,4],[6,8,10],[12,14,16]])


In [11]:
print(np.vstack((a,b)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [12]:
print(np.arange(9,-1,-1))

[9 8 7 6 5 4 3 2 1 0]


In [13]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.hsplit(a,3))

[array([[10],
       [40],
       [70]]), array([[20],
       [50],
       [80]]), array([[30],
       [60],
       [90]])]


In [15]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr = np.arange(10)
print(arr.reshape(2,-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
arr = np.arange(10)
arr_slice = arr[8:5]
arr_slice[:] = 69
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(np.concatenate([a,b],axis=0))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(np.vstack([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [22]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(np.r_[a,b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [24]:
a = np.array([[0,1,2,45],[3,4,5,7],[6,7,8,8]])
b = np.array([[0,2,4,47],[6,8,10,9],[12,14,16,7]])
print(np.dstack((a,b)))

[[[ 0  0]
  [ 1  2]
  [ 2  4]
  [45 47]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]
  [ 7  9]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]
  [ 8  7]]]


In [25]:
np.max(a)

45

In [28]:
a.max()

45

In [30]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b = np.array([[0,2,4],[6,8,10],[12,14,16]])
print(np.concatenate([a,b],axis=1))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [31]:
arr = np.array([67.98, -10.25, -22.06, 0.5, 12.90, 10.10])
print(arr.astype(np.int32))

[ 67 -10 -22   0  12  10]


In [32]:
arr = [0.3490, -1.4545, 1,204, -9.7152, 11.43, -0.8439]
arr.sort()
print(arr)

[-9.7152, -1.4545, -0.8439, 0.349, 1, 11.43, 204]


In [33]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b = np.array([[0,2,4],[6,8,10],[12,14,16]])
print(np.concatenate([b,a],axis=0))

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [34]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [41]:
a = np.array([0,1])
b = np.array([0,2])
print(np.column_stack((a,b)))

[[0 0]
 [1 2]]


In [42]:
names = (["Ali", "Neha", "Ali", "Hamza", 'neha', "Fatima", "Hamza"])

In [43]:
print(np.unique(names))

['Ali' 'Fatima' 'Hamza' 'Neha' 'neha']
